let allSongs = {
    1:['Take on Me','a-ha'],		
    2:['Billie Jean','Michael Jackson'],		
    3:['Every Breath You Take','The Police'],		
    4:['Africa','TOTO'],		
    5:['Girls Just Want to Have Fun','Cyndi Lauper'],		
    6:['Karma Chameleon - Remastered 2002','Culture Club'],		
    7:['Sweet Dreams (Are Made of This) - Remastered','Eurythmics, Annie Lennox, Dave Stewart'],		
    8:['Wake Me Up Before You Go-Go','Wham!'],		
    9:['Two Words','Retrofile'],		
    10:['Livin On A Prayer','Bon Jovi'],		
    11:['Stayin Alive','Bee Gees'],		
    12:['Dancing Queen','ABBA'],
    13:['Beat It','Michael Jackson'],		
    14:['Celebration','Kool & The Gang'],		
    15:['Kung Fu Fighting','Carl Douglas'],		
    16:['Romanticism','Retrofile'],		
    17:['Smooth Criminal - 2012 Remaster','Michael Jackson'],		
    18:['Youre The One That I Want - From “Grease”','John Travolta, Olivia Newton-John'],		
    19:['Tarzan Boy','Baltimora'],		
    20:['Walking On Sunshine','Katrina & The Waves'],		
    21:['Bad Dreams','Retrofile'],		
    22:['What A Feeling','Irene Cara'],		
    23:['We Built This City','Starship'],		
    24:['Jump - 2015 Remaster','Van Halen'],		
    25:['Tainted Love','Soft Cell'],		
    26:['Running','Retrofile'],		
    27:['99 Luftballons','Nena'],		
    28:['Video Killed The Radio Star','The Buggles'],		
    29:['Im Gonna Be (500 Miles)','The Proclaimers'],		
    30:['Dont Stop Believin','Journey'],		
    31:['Black or White - Single Version','Michael Jackson'],		
    32:['Never Gonna Give You Up','Rick Astley'],		
    33:['Material Girl','Madonna'],		
    34:['Uptown Girl','Billy Joel'],		
    35:['Take A Chance On Me','ABBA'],		
    36:['Dont You (Forget About Me)','Simple Minds'],		
    37:['Total Eclipse of the Heart','Bonnie Tyler'],		
    38:['Were Not Gonna Take It','Twisted Sister'],		
    39:['This','Vita Chino'],		
    40:['One Way Or Another - Remastered/2001','Blondie'],		
    41:['Hooked On A Feeling','Blue Swede, Björn Skifs'],		
    42:['Kids In America','Kim Wilde'],		
    43:['Dancing In the Dark','Bruce Springsteen'],		
    44:['Rivers of Babylon','Boney M.'],		
    45:['Always on My Mind','Pet Shop Boys'],		
    46:['Heard It All Before','Retrofile'],		
    47:['Dancing On The Ceiling','Lionel Richie'],		
    48:['Crocodile Rock','Elton John'],		
    49:['Freedom','Wham!'],		
    50:['Believe','Cher'],		
    51:['Poster Child','Retrofile'],		
    52:['Like a Prayer','Madonna'],		
    53:['Faith - Remastered','George Michael'],		
    54:['Time After Time','Cyndi Lauper'],		
    55:['I Remember You','Skid Row'],		
    56:['Thriller','Michael Jackson'],		
    57:['Call Me','Blondie'],		
    58:['Dig My Grave','Retrofile'],		
    59:['Like a Virgin','Madonna'],		
    60:['West End Girls - 2001 Remaster','Pet Shop Boys'],		
    61:['When Doves Cry','Prince'],		
    62:['Freedom in Your Eyes','Retrofile'],		
    63:['Walking On Sunshine (25th Anniversary) - 2010 Remaster','Katrina & The Waves'],		
    64:['Peace of Mind - Extended Dance Mix','Retrofile'],		
    65:['Holding Out for a Hero - From Footloose Soundtrack','Bonnie Tyler'],		
    66:['We Didnt Start the Fire','Billy Joel'],		
    67:['Dont You Want Me','The Human League'],		
    68:['The Final Countdown','Europe'],		
    69:['Losing Sleep','Retrofile'],		
    70:['Try So Hard - Single Version','Retrofile'],		
    71:['Sweater Weather','The Neighbourhood'],		
    72:['Pumped Up Kicks','Foster The People'],		
    73:['Safe And Sound','Capital Cities'],		
    74:['Walking On A Dream','Empire of the Sun'],		
    75:['The Nights','Avicii'],		
    76:['Midnight City','M83'],		
    77:['Viva La Vida','Coldplay'],		
    78:['Rude','MAGIC!'],		
    79:['Am I Wrong','Nico & Vinz'],		
    80:['Latch','Disclosure, Sam Smith'],		
    81:['Lean On','Major Lazer, MØ, DJ Snake'],		
    82:['Good Time','Owl City, Carly Rae Jepsen'],		
    83:['Cool Kids','Echosmith'],		
    84:['Fancy','Iggy Azalea, Charli XCX'],		
    85:['Glamorous','Fergie, Ludacris'],		
    86:['Only Girl (In The World)','Rihanna'],		
    87:['Memories (feat. Kid Cudi)','David Guetta, Kid Cudi'],		
    88:['Titanium (feat. Sia)','David Guetta, Sia'],		
    89:['All Time Low','Jon Bellion'],		
    90:['Dont You Worry Child','Swedish House Mafia, John Martin'],		
    91:['Dont Let Me Down','The Chainsmokers, Daya'],		
    92:['Closer','The Chainsmokers, Halsey'],		
    93:['Let Me Love You','DJ Snake, Justin Bieber'],		
    94:['Waves - Robin Schulz Radio Edit','Mr. Probz, Robin Schulz'],		
    95:['This Girl (Kungs Vs. Cookin On 3 Burners)','Kungs, Cookin On 3 Burners'],		
    96:['Somebody That I Used To Know','Gotye, Kimbra'],		
    97:['Little Talks','Of Monsters and Men'],		
    98:['Send Me An Angel','Real Life'],		
    99:['Applause','Lady Gaga'],		
    100:['Habits (Stay High)','Tove Lo'],		
    101:['Hymn for the Weekend','Coldplay'],		
    102:['Glad You Came','The Wanted'],		
    103:['Moves Like Jagger','Maroon 5, Christina Aguilera'],		
    104:['On The Floor - Radio Edit','Jennifer Lopez, Pitbull'],		
    105:['California Gurls','Katy Perry, Snoop Dogg'],		
    106:['Give Me Everything (feat. Ne-Yo, Afrojack & Nayer)','Pitbull, Ne-Yo, Afrojack, Nayer'],		
    107:['Time of Our Lives','Pitbull, Ne-Yo'],		
    108:['Feel This Moment (feat. Christina Aguilera)','Pitbull, Christina Aguilera'],		
    109:['Counting Stars','OneRepublic'],		
    110:['Radioactive','Imagine Dragons'],		
    111:['Lights','Ellie Goulding'],		
    112:['Shut Up and Dance','WALK THE MOON'],		
    113:['Rather Be (feat. Jess Glynne)','Clean Bandit, Jess Glynne'],		
    114:['Clarity','Zedd, Foxes'],		
    115:['Royals','Lorde'],		
    116:['Dark Horse','Katy Perry, Juicy J'],		
    117:['Black Widow','Iggy Azalea, Rita Ora'],		
    118:['Wide Awake','Katy Perry'],		
    119:['One Dance','Drake, Wizkid, Kyla'],		
    120:['Starboy','The Weeknd, Daft Punk'],		
    121:['My Way','Calvin Harris'],		
    122:['Dancin - Krono Remix','Aaron Smith, Luvli, Krono'],		
    123:['See You Again (feat. Charlie Puth)','Wiz Khalifa, Charlie Puth'],		
    124:['Stressed Out','Twenty One Pilots'],		
    125:['break up with your girlfriend, im bored','Ariana Grande'],		
    126:['Shake It Off','Taylor Swift'],		
    127:['Bad Blood','Taylor Swift, Kendrick Lamar'],		
    128:['Cool for the Summer','Demi Lovato'],		
    129:['Where Them Girls At (feat. Nicki Minaj & Flo Rida)','David Guetta, Flo Rida, Nicki Minaj'],		
    130:['I Knew You Were Trouble.','Taylor Swift'],		
    131:['Love The Way You Lie','Eminem, Rihanna'],		
    132:['Cant Hold Us (feat. Ray Dalton)','Macklemore & Ryan Lewis, Macklemore, Ryan Lewis, Ray Dalton'],		
    133:['Boom Clap','Charli XCX'],		
    134:['One Kiss (with Dua Lipa)','Calvin Harris, Dua Lipa'],		
    135:['Still into You','Paramore'],		
    136:['Telephone','Lady Gaga, Beyoncé'],		
    137:['Party Rock Anthem','LMFAO, Lauren Bennett, GoonRock'],		
    138:['Airplanes (feat. Hayley Williams of Paramore)','B.o.B, Hayley Williams'],		
    139:['Hey Mama (feat. Nicki Minaj, Bebe Rexha & Afrojack)','David Guetta, Afrojack, Bebe Rexha, Nicki Minaj'],		
    140:['Break Free','Ariana Grande, Zedd'],		
    141:['Same Old Love','Selena Gomez'],		
    142:['On My Mind','Ellie Goulding'],		
    143:['Teenage Dream','Katy Perry'],		
    144:['Heart Attack','Demi Lovato'],		
    145:['Worth It (feat. Kid Ink)','Fifth Harmony, Kid Ink'],		
    146:['Sorry','Justin Bieber'],		
    147:['Für Elise, WoO 59','Ludwig van Beethoven, Nelly Kokinos'],		
    148:['Sonata No. 14 Moonlight in C-Sharp Minor, Op. 27 No. 2: I. Adagio sostenuto','Ludwig van Beethoven, Paul Lewis'],		
    149:['Nocturne in C-sharp minor, B. 49','Frédéric Chopin, Brigitte Engerer'],		
    150:['The Four Seasons - Winter in F Minor, RV. 297: I. Allegro non molto','Antonio Vivaldi, Adrian Chandler, La Serenissima'],		
    151:['Tchaikovsky: The Nutcracker, Op. 71: Miniature Overture','Pyotr Ilyich Tchaikovsky, Berliner Philharmoniker, Sir Simon Rattle'],		
    152:['Cello Suite No. 1 in G Major, BWV 1007: I. Prélude','Johann Sebastian Bach, Yo-Yo Ma'],		
    153:['Suite Bergamasque, L. 75: III. Clair De Lune','Claude Debussy, Steve Anderson'],		
    154:['Orff: Carmina Burana, Introduction, Fortuna Imperatrix Mundi: O Fortuna','Carl Orff, Janice Watson, James Bowman, Donald Maxwell, Bournemouth Symphony Chorus, Waynflete Singers, Highcliffe Junior Choir, Bournemouth Symphony Orchestra, David Hill'],		
    155:['Peer Gynt-Suite Nr. 1, Op. 46: I. Morgenstemning (Morning Mood)','Edvard Grieg, BBC Scottish Symphony Orchestra, Jerzy Maksymiuk'],		
    156:['Carmen Suite No. 1: 5. Les toréadors','Georges Bizet, Orchestre de Paris, Semyon Bychkov'],		
    157:['The Nutcracker, Op. 71: Act II Tableau 3: Variation 2: Dance of the Sugar-Plum Fairy','Pyotr Ilyich Tchaikovsky, Russian National Orchestra, Mikhail Pletnev'],		
    158:['Rondo Alla Turca','PM Artist Sessions Project'],		
    159:['Strauss, R: Also sprach Zarathustra, Op. 30: I. Introduction','Richard Strauss, London Philharmonic Orchestra, David Bell, Klaus Tennstedt'],		
    160:['Carnival of the Animals, R. 125: Aquarium','Camille Saint-Saëns, Arthur Fiedler, Leo Litwin, Samuel Lipman, Martin Hoherman, Boston Pops Orchestra'],		
    161:['Piano Trio No. 2 In E Flat Major, Op. 100, D. 929: II. Andante Con Moto','Stuttgart Piano Trio, Franz Schubert'],		
    162:['The Flower Duet (From Lakmé)','Katherine Jenkins, Kiri Te Kanawa, Philharmonia Orchestra, Anthony Inglis'],		
    163:['The Blue Danube','Johann Strauss II, Eugene Ormandy'],		
    164:['Eine kleine Nachtmusik in G major, K 525: I. Allegro','London Symphony Orchestra'],		
    165:['Carmen Suite No. 2, Act I: Habanera','London Festival Orchestra, Alfred Scholz'],		
    166:['Symphony No. 7 in A, Op. 92: 2. Allegretto','Ludwig van Beethoven, London Symphony Orchestra, Antal Doráti'],		
    167:['Symphony No. 5 in C minor, Op. 67: 1. Allegro con brio','Ludwig van Beethoven, Royal Concertgebouw Orchestra, George Szell'],		
    168:['Tchaikovsky: Swan Lake, Op. 20, Act II: No. 10, Scene. Moderato','Pyotr Ilyich Tchaikovsky, André Previn, London Symphony Orchestra'],		
    169:['Prokofiev: Dance of the Knights (The Apprentice)','Sergei Prokofiev, Philadelphia Orchestra, Riccardo Muti'],		
    170:['Lacrimosa','Wolfgang Amadeus Mozart, Lisa Beckley, Elena Filipova, Magdaléna Hajóssyová, Peter Mikulas, Michel Piquemal, Gloria Scalchi, Michel Piquemal Vocal Ensemble, Hungarian State Opera Chorus, Oxford Schola Cantorum, Slovak Philharmonic Chorus, Hungarian State Opera Orchestra, Orchestre De La Cite, Oxford Camerata, Slovak Philharmonic'],		
    171:['Merry-Go-Round of Life - from Howls Moving Castle','Joe Hisaishi'],		
    172:['Chopin: Nocturne No. 20 in C-Sharp Minor, Op. Posth.','Frédéric Chopin, Mikhail Pletnev'],		
    173:['Miroirs: III. Une barque sur locéan','Maurice Ravel, André Laplante'],		
    174:['The French Library','Franz Gordon'],		
    175:['The Piano Duet','Danny Elfman'],		
    176:['Victors Piano Solo','Danny Elfman'],		
    177:['Une Barque Sur Locéan from Miroirs','André Laplante'],		
    178:['Romeo and Juliet, Op. 64 / Act 1: Dance Of The Knights','Sergei Prokofiev, Cleveland Orchestra, Lorin Maazel'],		
    179:['Carmen, Act I: No.5 Habanera : Lamour est un oiseau rebelle (Carmen/Cigarières/Jeunes gens/Dragons)','Georges Bizet, Angela Gheorghiu, Michel Plasson, Wolff, Orchestre National Du Capitole De Toulouse'],		
    180:['What Falling in Love Feels Like - Cover','Gabriel Ozelame'],		
    181:['Waltz Of The Flowers From The Nutcracker','Pyotr Ilyich Tchaikovsky, Royal Philharmonic Orchestra, David Arnold'],		
    182:['Overture - From The Phantom Of The Opera Motion Picture','Andrew Lloyd Webber'],		
    183:['Waltz No.2','Cihat Aşkın'],		
    184:['Liebestraume, S541/R211 : No. 3: Nocturne in A-Flat Major','Franz Liszt, Jenő Jandó'],		
    185:['21 Hungarian Dances, WoO 1: No. 5 in G Minor: Allegro','Johannes Brahms, Wiener Philharmoniker, Claudio Abbado'],		
    186:['Handel / Orch. Hale: Keyboard Suite No. 4 in D Minor, HWV 437: III. Sarabande','George Frideric Handel, Alexander Briger, Academy of St. Martin in the Fields'],		
    187:['Nocturne en Mi Bémol Majeur, Op. 9 No. 2','Frédéric Chopin, Luis Fernando Pérez'],		
    188:['Serenade for Strings in E Major, Op. 22, B. 52: II. Tempo di valse','Antonín Dvořák, Prague Chamber Orchestra, Petr Skvor'],		
    189:['Jazz Suite No. 2: VI. Waltz 2','Dmitri Shostakovich, Russian State Symphony Orchestra, Dmitry Yablonsky'],		
    190:['Suite Bergamasque, L. 75: III. Clair de lune (Andante très expressif)','Claude Debussy, Alain Planès'],		
    191:['Requiem, K. 626: Lacrimosa','Wolfgang Amadeus Mozart, Michael Finnissy, Academy of Ancient Music, Stephen Cleobury, Choir of Kings College\, Cambridge'],		
    192:['The Carnival of the Animals, R. 125: XIII. The Swan (Arr. for Cello and Piano)','Camille Saint-Saëns, Yo-Yo Ma, Kathryn Stott'],		
    193:['Tchaikovsky: The Nutcracker, Op. 71, Act II: No. 13, Waltz of the Flowers','Pyotr Ilyich Tchaikovsky, Berliner Philharmoniker, Sir Simon Rattle'],		
    194:['Serenade In G Major Eine Kleine Nachtmusik, K. 525: I. Allegro','Wolfgang Amadeus Mozart, The English Concert, Andrew Manze'],		
    195:['Ave Maria','Charles Gounod, Yo-Yo Ma'],		
    196:['Violin Concerto BWV 1042 in E Major: Violin Concerto BWV 1042 in E Major: I. Allegro','Johann Sebastian Bach, Freiburger Barockorchester, Gottfried Von Der Goltz'],		
    197:['Danse macabre in G Minor, Op. 40','Camille Saint-Saëns, Slovak Radio Symphony Orchestra, Keith Clark'],		
    198:['Prokofiev: Romeo and Juliet, Op. 64, Act 1, Scene 2: Dance of the Knights','Sergei Prokofiev, André Previn, London Symphony Orchestra'],		
    199:['Symphony No. 5 in C Minor, Op. 67: I. Allegro con brio','Ludwig van Beethoven, Wiener Philharmoniker, Carlos Kleiber'],		
    200:['4 Impromptus, Op. 90, D.899: No. 4 in A Flat Major: Allegretto','Franz Schubert, Radu Lupu'],		
    201:['Le Nozze di Figaro, K. 492: Sinfonia','Wolfgang Amadeus Mozart, René Jacobs, Concerto Köln'],		
    202:['Orchestral Suite No. 3 in D Major, BWV 1068: II. Air On a G String (Arr. for Piano)','Johann Sebastian Bach, Lang Lang'],		
    203:['Pachelbel: Canon and Gigue for Three Violins and Continuo in D Major: Canon','Johann Pachelbel, Sir Neville Marriner, Academy of St. Martin in the Fields'],		
    204:['Gnossienne: No. 1','Erik Satie, Alexandre Tharaud'],		
    205:['Piano Sonata No. 12 in F Major, K. 332: II. Adagio','Wolfgang Amadeus Mozart, Maria João Pires'],		
    206:['La traviata / Act I: Libiamo nelieti calici','Giuseppe Verdi, Ileana Cotrubas, Plácido Domingo, Chor der Bayerischen Staatsoper München, Bavarian State Orchestra, Carlos Kleiber'],		
    207:['Rhapsody on a Theme of Paganini, Op. 43: Variation No. 18 Andante cantabile','Sergei Rachmaninoff, Daniil Trifonov, Philadelphia Orchestra, Yannick Nézet-Séguin'],		
    208:['Elgar: Cello Concerto in E Minor, Op. 85: I. Adagio - Moderato','Edward Elgar, Jacqueline du Pré, London Symphony Orchestra, Sir John Barbirolli'],		
    209:['Piano Concerto in A Minor, Op. 16: I. Allegro molto moderato','Edvard Grieg, Javier Perianes, BBC Symphony Orchestra, Sakari Oramo'],		
    210:['Symphony No. 40 in G Minor, K. 550: I. Molto allegro','Wolfgang Amadeus Mozart, Riccardo Minasi, Ensemble Resonanz'],		
    211:['Mahler: Symphony No. 5 in C-Sharp Minor: IV. Adagietto. Sehr langsam','Gustav Mahler, Daniel Barenboim, Chicago Symphony Orchestra'],		
    212:['An der schönen blauen Donau, Op.314','Johann Strauss II, Berliner Philharmoniker, Herbert von Karajan'],		
    213:['Suite No. 3 in D Major, BWV 1068: II. Air','Johann Sebastian Bach, David Bell, Berliner Philharmoniker, Herbert von Karajan'],		
    214:['Liebestraum No. 3 in A-Flat Major, S. 541 / 3','Franz Liszt, Lang Lang'],		
    215:['Barber: Adagio for Strings, Op. 11','Samuel Barber, Sir Simon Rattle, Berliner Philharmoniker'],		
    216:['Vivaldi Variation (Arr. for Piano from Concerto for Strings in G Minor, RV 156)','Antonio Vivaldi, Florian Christl'],		
    217:['Vivaldi: The Four Seasons, Violin Concerto in G Minor, Op. 8 No. 2, RV 315 Summer: III. Presto','Antonio Vivaldi, Nigel Kennedy, English Chamber Orchestra'],		
    218:['Buy Dirt','Jordan Davis, Luke Bryan'],		
    219:['Quittin Time','Zach Bryan'],		
    220:['All Yourn','Tyler Childers'],		
    221:['Whiskey Glasses','Morgan Wallen'],		
    222:['Forever After All','Luke Combs'],		
    223:['Boot Scootin Boogie','Brooks & Dunn'],		
    224:['Country Girl (Shake It For Me)','Luke Bryan'],		
    225:['Shes Country','Jason Aldean'],		
    226:['Alright','Darius Rucker'],		
    227:['Caught Up In The Country','Rodney Atkins, The Fisk Jubilee Singers'],		
    228:['Chicken Fried','Zac Brown Band'],		
    229:['Five More Minutes','Scotty McCreery'],		
    230:['Chasin You','Morgan Wallen'],		
    231:['Live Like You Were Dying','Tim McGraw'],		
    232:['Big Green Tractor','Jason Aldean'],		
    233:['Write This Down','George Strait'],		
    234:['Til You Cant','Cody Johnson'],		
    235:['In Case You Didnt Know','Brett Young'],		
    236:['Break Up In A Small Town','Sam Hunt'],		
    237:['Drunk On A Plane','Dierks Bentley'],		
    238:['Colder Weather','Zac Brown Band'],		
    239:['Sand In My Boots','Morgan Wallen'],		
    240:['It Dont Hurt Like It Used To','Billy Currington'],		
    241:['Drink In My Hand','Eric Church'],		
    242:['She Got the Best of Me','Luke Combs'],		
    243:['Buy Me a Boat','Chris Janson'],		
    244:['Unforgettable','Thomas Rhett'],		
    245:['Dirt Road Anthem','Jason Aldean'],		
    246:['What Was I Thinkin','Dierks Bentley'],		
    247:['Wasted On You','Morgan Wallen'],		
    248:['Slow Dance In A Parking Lot','Jordan Davis'],		
    249:['Do I Make You Wanna','Billy Currington'],		
    250:['How Do You Like Me Now?!','Toby Keith'],		
    251:['Beer Never Broke My Heart','Luke Combs'],		
    252:['Redneck Yacht Club','Craig Morgan'],		
    253:['Burning Man','Dierks Bentley, Brothers Osborne'],		
    254:['Love Like Crazy','Lee Brice'],		
    255:['Got What I Got','Jason Aldean'],		
    256:['Play It Again','Luke Bryan'],		
    257:['Somebody’s Problem','Morgan Wallen'],		
    258:['Simple','Florida Georgia Line'],		
    259:['Like I Loved You','Brett Young'],		
    260:['Blue Tacoma','Russell Dickerson'],		
    261:['Big, Big Plans','Chris Lane'],		
    262:['Living','Dierks Bentley'],		
    263:['Youre Gonna Miss This','Trace Adkins'],		
    264:['Pretty Good At Drinkin Beer','Billy Currington'],		
    265:['Even If It Breaks Your Heart','Eli Young Band'],		
    266:['You Proof','Morgan Wallen'],		
    267:['Small Town Boy','Dustin Lynch'],		
    268:['This Is Country Music','Brad Paisley'],		
    269:['Old Alabama (feat. Alabama)','Brad Paisley, Alabama'],		
    270:['A Man Dont Have to Die','Brad Paisley'],		
    271:['Camouflage','Brad Paisley'],		
    272:['Remind Me (with Carrie Underwood)','Brad Paisley, Carrie Underwood'],		
    273:['Working On a Tan','Brad Paisley'],		
    274:['Love Her Like Shes Leavin (feat. Don Henley)','Brad Paisley, Don Henley'],		
    275:['One of Those Lives','Brad Paisley'],		
    276:['Toothbrush','Brad Paisley'],		
    277:['Be the Lake','Brad Paisley'],		
    278:['Eastwood (feat. Clint Eastwood)','Brad Paisley, Clint Eastwood'],		
    279:['New Favorite Memory','Brad Paisley'],		
    280:['Dont Drink the Water (feat. Blake Shelton)','Brad Paisley, Blake Shelton'],		
    281:['I Do Now','Brad Paisley'],		
    282:['Lifes Railway to Heaven (feat. Marty Stuart, Sheryl Crow & Carl Jackson)','Brad Paisley, Marty Stuart, Sheryl Crow, Carl Jackson'],		
    283:['Tsunami - Original Mix','DVBBS, Borgeous'],		
    284:['Rattle - Original Mix','Bingo Players'],		
    285:['Immortal (We Live Forever) - Original Mix','DVBBS, Tony Junior'],		
    286:['Five Hours','Deorro'],		
    287:['Daydreamer (feat. Example) - Radio Edit','Flux Pavilion, Example'],		
    288:['Let It Rain','Keys N Krates'],		
    289:['Flute - Radio Edit','New World Sound, Thomas Newson'],		
    290:['Youth (Adventure Club Remix)','Foxes'],		
    291:['Gold (feat. Yuna)','Adventure Club, Yuna'],		
    292:['Fade (feat. Zak Waters)','Adventure Club, Zak Waters'],		
    293:['The Hum','Dimitri Vegas & Like Mike, Ummet Ozcan'],		
    294:['Hydroplane','Kudo and Fish'],		
    295:['Toca (feat. Timmy Trumpet & KSHMR)','Carnage, Timmy Trumpet, KSHMR'],		
    296:['Big Bang (2015 Life In Color Anthem) - Radio Edit','Borgeous, SOLANO'],		
    297:['Perdoname (feat. DyCy & Adrian Delgado)','Deorro, DyCy, Adrian Delgado'],		
    298:['Disarm You (Isaac Berge Remix) [feat. Ilsey]','Kaskade, Ilsey'],		
    299:['The Sound (feat. Junkie Kid)','Carnage, Junkie Kid'],		
    300:['Pillz (feat. Green Velvet)','Flosstradamus, Yellow Claw, Green Velvet'],		
    301:['Wonder (feat. The Kite String Tangle)','Adventure Club, The Kite String Tangle'],		
    302:['We Rise','San Holo'],		
    303:['Lonely Nights','JD Beatz'],		
    304:['Breathless ft. Michelle Quezada - Regulators Remix','Candyland, Regulators'],		
    305:['Andale (feat. Lil Jon)','Wildfellaz, Problem, Lil Jon'],		
    306:['Melody','Dimitri Vegas & Like Mike, Steve Aoki, Ummet Ozcan'],		
    307:['U Dont Know - Slander Remix','Alison Wonderland, Wayne Coyne, SLANDER'],		
    308:['Bring Back the Summer (feat. OLY)','Rain Man, Oly'],		
    309:['Drop That Low (When I Dip)','Tujamo'],		
    310:['Overload - The Chainsmokers Remix','Life of Dillon'],		
    311:['No Money','Galantis'],		
    312:['Bouncer','Showtek, Ookay'],		
    313:['Ocho Cinco','DJ Snake, Yellow Claw'],		
    314:['Light','San Holo'],		
    315:['Ready For Action','Dimitri Vegas & Like Mike'],		
    316:['The Meaning','Gent & Jawns'],		
    317:['Champion Sound','Gent & Jawns'],		
    318:['2 MUCH (feat. 24hrs) (feat. 24hrs)','Flosstradamus, 24hrs'],		
    319:['My Night (feat. 070 Shake)','Keys N Krates, 070 Shake'],		
    320:['AINT NO PARTY','Quintino'],		
    321:['Path Of The Hunter','Headhunterz'],		
    322:['Sinfonia','Mark Sixma'],		
    323:['Shakalaka (Steve Aoki, Deorro, MAKJ & Max Styler)','Steve Aoki, Deorro, MAKJ, Max Styler'],		
    324:['Summertime','Yellow Claw, San Holo'],		
    325:['Brasil Connect','Quintino'],		
    326:['The Riddle','Bassjackers'],		
    327:['Dracarys','Deorro, Dirty Audio'],		
    328:['MOP','Borgore, Gucci Mane, THIRTY RACK'],		
    329:['ID','Boombox Cartel, Flosstradamus'],		
    330:['Who Wouldve Thought','CryJaxx, Reeck, Drama B'],		
    331:['Rave Culture','W&W'],		
    332:['G.O.D. (GRIND OR DIE) [feat. Leateq]','BLVK JVCK, Flosstradamus, Leateq'],		
    333:['Arcus','RL Grime, graves'],		
    334:['Ferrari (feat. Afrojack)','Cheat Codes, Afrojack'],		
    335:['Without Me - ILLENIUM Remix','Halsey, ILLENIUM'],		
    336:['Broken','Honors, Prismo'],		
    337:['Takillya','Vinnie Maniscalco'],		
    338:['Music To My Ears (feat. Tory Lanez)','Keys N Krates, Tory Lanez'],		
    339:['Love Me Like You Used To','Kaskade, Cecilia Gault'],		
    340:['Demons (feat. RUNN)','Bear Grillz, RUNN'],		
    341:['Like That','NGHTMRE, Big Gigantic'],		
    342:['Flip The Beat','Bassjackers, APEK'],		
    343:['SouthSide','DJ Snake, Eptic'],		
    344:['Nothing To Hide','Boombox Cartel, Karra'],		
    345:['Fat Beat','Will Sparks, Danny Avila'],		
    346:['Matrix','W&W, Maurice West'],		
    347:['No Regrets (feat. Krewella)','KSHMR, Yves V, Krewella'],		
    348:['GOMF (feat. BRIDGE)','DVBBS, BRIDGE'],		
    349:['NEW WIP','Boombox Cartel, MadeinTYO'],		
    350:['Gore On The Dancefloor','Borgore, MOONBOY, Rico Act'],		
    351:['Let The Music Take Control','W&W, Blasterjaxx'],		
    352:['Hurt - NGHTMRE Remix','Oliver Tree, NGHTMRE'],		
    353:['Sweater Weather','The Neighbourhood'],		
    354:['Freaks','Surf Curse'],		
    355:['Cold Cold Cold','Cage The Elephant'],		
    356:['My Number','Foals'],		
    357:['Always Like This','Bombay Bicycle Club'],		
    358:['Evil','Interpol'],		
    359:['Australia','The Shins'],		
    360:['What You Know','Two Door Cinema Club'],		
    361:['Norgaard','The Vaccines'],		
    362:['You Only Live Once','The Strokes'],		
    363:['Snap Out Of It','Arctic Monkeys'],		
    364:['Do You Want To','Franz Ferdinand'],		
    365:['1901','Phoenix'],		
    366:['Oceans Deep','Born Ruffians'],		
    367:['Banquet','Bloc Party'],		
    368:['Cmere','Interpol'],		
    369:['Hard to Beat','Hard-FI'],		
    370:['When The Sun Goes Down','Arctic Monkeys'],		
    371:['When Am I Gonna Lose You','Local Natives'],		
    372:['If You Wanna','The Vaccines'],		
    373:['Two Weeks','Grizzly Bear'],		
    374:['Friends','Sure Sure'],		
    375:['Slow Hands','Interpol'],		
    376:['She Moves In Her Own Way','The Kooks'],		
    377:['From The Ritz To The Rubble','Arctic Monkeys'],		
    378:['Hang Me Up To Dry','Cold War Kids'],		
    379:['Fire','Kasabian'],		
    380:['New Slang - 2021 Remaster','The Shins'],		
    381:['Lisztomania','Phoenix'],		
    382:['Maps','Yeah Yeah Yeahs'],		
    383:['Obstacle 1 - 2012 Remaster','Interpol'],		
    384:['Twice','Catfish and the Bottlemen'],		
    385:['Sticks N Stones','Jamie T'],		
    386:['Phantom Limb','The Shins'],		
    387:['A Certain Romance','Arctic Monkeys'],		
    388:['Always Where I Need To Be','The Kooks'],		
    389:['Farewell To The Fairground','White Lies'],		
    390:['T-Shirt Weather','Circa Waves'],		
    391:['Ruby','Kaiser Chiefs'],		
    392:['Rest My Chemistry','Interpol'],		
    393:['The Skin of My Yellow Country Teeth','Clap Your Hands Say Yeah'],		
    394:['Homesick','Catfish and the Bottlemen'],		
    395:['Houdini','Foster The People'],		
    396:['Same Jeans','The View'],		
    397:['Mardy Bum','Arctic Monkeys'],		
    398:['Neighborhood #2 (Laika)','Arcade Fire'],		
    399:['A-Punk','Vampire Weekend'],		
    400:['Now & Then','Sjowgren'],		
    401:['Down the Line','Beach Fossils'],		
    402:['Dont Look Back into the Sun','The Libertines'],		
    403:['Holding your hand (for the last time)','Sunburzt'],		
    404:['Everybody Talks','Neon Trees'],		
    405:['welcome and goodbye','Dream\, Ivory'],		
    406:['505','Arctic Monkeys'],		
    407:['Let U Go','Peach Tree Rascals'],		
    408:['Crimewave','Crystal Castles, HEALTH'],		
    409:['mr. sunshine','Yxngxr1'],		
    410:['Beige Bouquet','The Thing'],		
    411:['Calling My Name','Era'],		
    412:['Keep All That','Rich Amiri'],		
    413:['2 DOGS 1 LEASH','Noah Guy'],		
    414:['Once Upon a Time in Fucking Hollywood','Aaryan Shah'],		
    415:['Ancient One','Amyrion'],		
    416:['Force Field','Aidan Carroll'],		
    417:['Jealous','Eyedress'],		
    418:['Tripping Over Air','Aidan Bissett'],		
    419:['ill die anyway.','girl in red'],		
    420:['Patience','Steven Curtis'],		
    421:['Little Dark Age','MGMT'],		
    422:['Your Potion','Amyrion'],		
    423:['The Less I Know The Better','Tame Impala'],		
    424:['Take Five','Dave Brubeck'],		
    425:['So What (feat. John Coltrane, Cannonball Adderley & Bill Evans)','Miles Davis, John Coltrane, Cannonball Adderley, Bill Evans'],		
    426:['Strange Fruit','Billie Holiday'],		
    427:['A Love Supreme, Pt. I – Acknowledgement','John Coltrane'],		
    428:['Birdland','Weather Report'],		
    429:['What A Wonderful World','Louis Armstrong'],		
    430:['Feeling Good','Nina Simone'],		
    431:['At Last - Single Version','Etta James'],		
    432:['Round Midnight','Thelonious Monk'],		
    433:['The Girl From Ipanema','Stan Getz, João Gilberto, Astrud Gilberto'],		
    434:['Goodbye Pork Pie Hat','Charles Mingus'],		
    435:['In A Sentimental Mood','Duke Ellington, John Coltrane'],		
    436:['My Funny Valentine','Chet Baker'],		
    437:['Sing, Sing, Sing','Benny Goodman'],		
    438:['Body and Soul - 2000 Remastered Version','Coleman Hawkins'],		
    439:['Cantaloupe Island - Remastered','Herbie Hancock'],		
    440:['Moanin','Art Blakey & The Jazz Messengers'],		
    441:['St. Thomas','Sonny Rollins'],		
    442:['Song For My Father','Horace Silver'],		
    443:['Autumn Leaves','Cannonball Adderley'],		
    444:['A Night In Tunisia','Dizzy Gillespie'],		
    445:['All of Me','Ella Fitzgerald, Gerald Marks, SEYMOUR SIMONS'],		
    446:['All The Things You Are','Dizzy Gillespie'],		
    447:['Anthropology','Charlie Parker'],		
    448:['Autumn Leaves','Chet Baker'],		
    449:['Blue bossa','Dexter Gordon'],		
    450:['Blue Skies','Doris Day'],		
    451:['Body And Soul','Stan Getz'],		
    452:['But Not For Me - Vocal Version','Chet Baker'],		
    453:['Caravan','Thelonious Monk'],		
    454:['Chameleon','Herbie Hancock'],		
    455:['Corcovado (Quiet Nights Of Quiet Stars)','Stan Getz, João Gilberto, Astrud Gilberto, Antônio Carlos Jobim'],		
    456:['Desafinado','Antônio Carlos Jobim'],		
    457:['Embraceable You','Ella Fitzgerald'],		
    458:['Dream A Little Dream Of Me - Single Version','Ella Fitzgerald, Louis Armstrong'],		
    459:['Fascinating Rhythm','Ella Fitzgerald'],		
    460:['Fly Me To The Moon (In Other Words)','Frank Sinatra, Count Basie'],		
    461:['Footprints - Remastered','Wayne Shorter'],		
    462:['Georgia On My Mind','Oscar Peterson Trio'],		
    463:['Giant Steps','John Coltrane'],		
    464:['I Got Rhythm','Charlie Parker'],		
    465:['In the Mood','Glenn Miller'],		
    466:['It Dont Mean a Thing (If It Aint Got That Swing)','Duke Ellington'],		
    467:['How High The Moon - 1st Take','Ella Fitzgerald'],		
    468:['La vie en rose - Single Version','Louis Armstrong'],		
    469:['Lullaby Of Birdland','Ella Fitzgerald'],		
    470:['Maiden Voyage - Remastered','Herbie Hancock'],		
    471:['Mas, Que Nada!','Jorge Ben Jor'],		
    472:['Milestones (feat. John Coltrane, Cannonball Adderley, Red Garland, Paul Chambers & Philly Joe Jones)','Miles Davis, John Coltrane, Cannonball Adderley, Red Garland, Paul Chambers, Philly Joe Jones'],		
    473:['Misty','Stan Getz'],		
    474:['My Favorite Things - Remastered','The Dave Brubeck Quartet, Dave Brubeck'],		
    475:['My Foolish Heart - Live','Bill Evans Trio'],		
    476:['One OClock Jump','Count Basie'],		
    477:['Over The Rainbow','Ella Fitzgerald'],		
    478:['Satin Doll','Duke Ellington'],		
    479:['Solar - Rudy Van Gelder Remaster','Miles Davis Quintet'],		
    480:['Spain - Composite Alternative Take','Chick Corea'],		
    481:['St. Louis Blues','The Dave Brubeck Quartet'],		
    482:['Summertime','Louis Armstrong, Ella Fitzgerald'],		
    483:['Take Five','The Dave Brubeck Quartet'],		
    484:['Take the A Train','Duke Ellington'],		
    485:['The Girl From Ipanema','Antônio Carlos Jobim'],		
    486:['There Will Never Be Another You','Lester Young, Oscar Peterson Trio'],		
    487:['They Cant Take That Away From Me','Sarah Vaughan'],		
    488:['Walkin','Miles Davis'],		
    489:['Waltz for Debby (take 1) - Alternate Take','Bill Evans Trio'],		
    490:['Flower of Memories','Tenno'],		
    491:['Ascending To Heaven','Amess'],		
    492:['Spring Rain','BVG'],		
    493:['The Old Legend','DaniSogen'],		
    494:['Anomaly','Purrple Cat'],		
    495:['Peaceful Warrior','DaniSogen'],		
    496:['Warm Nights','A[way]'],		
    497:['Miasu','DaniSogen'],		
    498:['Garden','Kayba, Lomme'],		
    499:['Kugelblitz','Purrple Cat'],		
    500:['Natures Temple','Tenno'],		
    501:['moonbeams','jaackson, Lofty, Whilst'],		
    502:['Dancing in the Dark','Mondo Loops, Aiguille'],		
    503:['The Player','Cosmic Koala, Lucid Keys, Paul Indigo'],		
    504:['Winter Shells','Mondo Loops, Kanisan'],		
    505:['out of blue','jsan'],		
    506:['Healing Touch','DaniSogen'],		
    507:['42','Purrple Cat'],		
    508:['Pure Bliss','SPEECHLESS'],		
    509:['Beautiful Days','Cosmic Koala, Lucid Keys'],		
    510:['In Between Cycles','Sleepermane'],		
    511:['Lost Tapes','softy'],		
    512:['Runaway','Hevi, Kainbeats'],		
    513:['Soothe','Cosmic Koala, Lucid Keys'],		
    514:['The Way Out','Dimension 32'],		
    515:['Creations','xander., Tonion'],		
    516:['Nei','DaniSogen'],		
    517:['Defensive','xander., Philip Somber'],		
    518:['Dissipate','Purrple Cat'],		
    519:['After The Reign','Dimension 32, The Scandi'],		
    520:['On My Own','Yasumu'],		
    521:['Cloudy Springs','Kainbeats, softy'],		
    522:['Lavender','Kupla'],		
    523:['Childlike Wonder','Tibeauthetraveler, Lawrence Walther'],		
    524:['Capturing the Light','less.people'],		
    525:['Reflection','brillion.'],		
    526:['Willows','Sebastian Kamae, Intoku'],		
    527:['Moonwinds','Purrple Cat'],		
    528:['Under Your Spell','Dimension 32'],		
    529:['Sundials','Cosmic Koala, Lucid Keys'],		
    530:['message in a bottle','chief.'],		
    531:['Fairy Tales','Cosmic Koala, Lucid Keys'],		
    532:['Wildflower','Blue Wednesday'],		
    533:['Biomes','Casiio, Sleepermane'],		
    534:['Lacrima Rossa','Dimension 32'],		
    535:['Dahlia','no ones perfect, Kanisan'],		
    536:['Beneath The Surface','Yasumu, Amess'],		
    537:['Floating','Sebastian Kamae, Epona'],		
    538:['Obscura Luna','Dimension 32, Kanisan, Wishes and Dreams'],		
    539:['Unravel','Yasumu'],		
    540:['Space Pirates','Purrple Cat'],		
    541:['Walk Out','Khutko, Blue Wednesday'],		
    542:['Reflection','HoKø, Yoann Garel, Damien Fleau'],		
    543:['Ethereal','Hevi, H.1'],		
    544:['Dinner Talks','Dyrean, Nuver'],		
    545:['Affection','Casiio'],		
    546:['Complex Visions','Dimension 32'],		
    547:['Home','Tenno'],		
    548:['Sinking Fatigue','Raimu'],		
    549:['takeoff','stream_error'],		
    550:['Sweet Meetings','Cosmic Koala, Lucid Keys, Dimension 32'],		
    551:['Out There','Purrple Cat'],		
    552:['Introvert','Tenno'],		
    553:['Light In The Dark','Dimension 32'],		
    554:['Icarus','Casiio, Sleepermane'],		
    555:['Flying Colours','Amess'],		
    556:['Dreamscape','Spencer Hunt'],		
    557:['Distant','Tibeauthetraveler, Trix.'],		
    558:['Tziporrah','Amess'],		
    559:['Kukui Leaves','Phlocalyst, Mr. Käfer'],		
    560:['Mourning Dove','WYS, Sweet Medicine'],		
    561:['Distant Thoughts','Towerz, Hoogway'],		
    562:['Teahouse Spirits','Kalaido'],		
    563:['Sunrise Over Casablanca','Amess'],		
    564:['Pandora','Casiio, Sleepermane'],		
    565:['DAYDREAM','DESTIN CONRAD'],		
    566:['Bad Habit','Steve Lacy'],		
    567:['Today','Q'],		
    568:['Shut up My Moms Calling','Hotel Ugly'],		
    569:['EN ROUTE','HAWA'],		
    570:['The Greatest Smile','SAULT'],		
    571:['Hotel','Montell Fish'],		
    572:['best','greek'],		
    573:['Seltzer','Cruza'],		
    574:['Static','Steve Lacy'],		
    575:['All For You','Amaria, DESTIN CONRAD'],		
    576:['Them Changes','Thundercat'],		
    577:['supernova','Fousheé'],		
    578:['Awkward','SZA'],		
    579:['As Days Go By','Paulade'],		
    580:['Fall in Love with You.','Montell Fish'],		
    581:['END OF DAYS','Floyd Fuji'],		
    582:['Please Do Not Lean (feat. BADBADNOTGOOD)','Daniel Caesar, BADBADNOTGOOD'],		
    583:['The Dress','Dijon'],		
    584:['Feeling Myself','Nick Hakim'],		
    585:['Wildfires','SAULT'],		
    586:['IN THE AIR (SPED UP)','DESTIN CONRAD'],		
    587:['Sneaky','Duckwrth, Juls'],		
    588:['Louphoria (with Cruza)','Smino, Cruza'],		
    589:['What About Me?','Dayo Bello'],		
    590:['Killing Me','Omar Apollo'],		
    591:['Mad Riches','Sonder'],		
    592:['Exscape','Montell Fish'],		
    593:['Pink + White - Live at Electric Lady','Remi Wolf'],		
    594:['Shameless','Avenoir'],		
    595:['Lucky Me','Flwr Chyld, Sebastian Mikael'],		
    596:['Stereo Driver','Q'],		
    597:['ARMS (Edit)','SIPHO.'],		
    598:['THE SEASON (feat. PawPaw Rod)','Sherwyn, PawPaw Rod'],		
    599:['Deep Green','Christian Kuria'],		
    600:['Love Songz','dreamcastmoe, ZDBT'],		
    601:['Lee & Lovie (with reggie)','Smino, reggie'],		
    602:['Last Dance','Montell Fish'],		
    603:['safety','greek'],		
    604:['Rider','Mereba'],		
    605:['Stayed at the Party','Hope Tala'],		
    606:['2 DOGS 1 LEASH','Noah Guy'],		
    607:['I Love You More Than You Know (feat. Childish Gambino)','bLAck pARty, Childish Gambino'],		
    608:['Blame','Gabriels'],		
    609:['Divide','RealestK'],		
    610:['D4U - Spotify Singles','Avenoir'],		
    611:['Fool 4 U','Yuna'],		
    612:['Keep It Lo','Ojerime, Mura Masa'],		
    613:['careless (feat. daniel caesar)','FKA twigs, Daniel Caesar'],		
    614:['Ce Soir','Duckwrth, Syd'],		
    615:['Xtasy (Remix) [feat. Doechii]','Ravyn Lenae, Doechii'],		
    616:['Stuck In The Middle','Greentea Peng'],		
    617:['IDC','Jordan Ward, Joony'],		
    618:['I Think I Do','RealestK'],		
    619:['Relax and Run (feat. Erika de Casier & Eva Tolkin)','Blood Orange, Erika de Casier, Eva Tolkin'],		
    620:['Sinner','Kelz'],		
    621:['Sunbleach','Christian Kuria'],		
    622:['Luvaroq','Elujay, serpentwithfeet'],		
    623:['Goodbye Paris','Santino Le Saint'],		
    624:['WHOSE LOVE (feat. Tempest)','Naomi Wild, Tempest'],		
    625:['Figures','Gaidaa'],		
    626:['Trust','RealestK'],		
    627:['bend yr ear','Son Little'],		
    628:['Bliss','Amber Mark'],		
    629:['moonlit room','UMI'],		
    630:['NEW ORLEANS','BROCKHAMPTON'],		
    631:['YuNg BrAtZ','XXXTENTACION'],		
    632:['44 More','Logic'],		
    633:['Zenith','Denzel Curry, Joey Bada$$'],		
    634:['Do Not Disturb (feat. Lil Yachty & Offset)','Smokepurpp, Murda Beatz, Lil Yachty, Offset'],		
    635:['Ni**as In Paris','JAY-Z, Kanye West'],		
    636:['Sweet Thangs','Tee Grizzley'],		
    637:['Shabba (feat. A$AP Rocky)','A$AP Ferg, A$AP Rocky'],		
    638:['Mase in 97','Carnage, Lil Yachty'],		
    639:['CLOUT COBAIN | CLOUT CO13A1N','Denzel Curry'],		
    640:['GOSHA','$NOT'],		
    641:['Alright','Kendrick Lamar'],		
    642:['Ric Flair Drip (with Metro Boomin)','Offset, Metro Boomin'],		
    643:['Forgot About Dre','Dr. Dre, Eminem'],		
    644:['Hands On The Wheel','ScHoolboy Q, A$AP Rocky'],		
    645:['STARGAZING','Travis Scott'],		
    646:['Wait a Minute','PHresher'],		
    647:['Ambitionz Az A Ridah','2Pac'],		
    648:['Hella Hoes (feat. A$AP Rocky, A$AP Ferg, A$AP Nast & A$AP Twelvyy)','A$AP Mob, A$AP Rocky, A$AP Ferg, A$AP NAST, A$AP Twelvyy'],		
    649:['Still D.R.E.','Dr. Dre, Snoop Dogg'],		
    650:['Wiley Flow','Stormzy'],		
    651:['Who Dat Boy (feat. A$AP Rocky)','Tyler\, The Creator, A$AP Rocky'],		
    652:['Fingers Blue (feat. Travis Scott)','Smokepurpp, Travis Scott'],		
    653:['Immortal','21 Savage'],		
    654:['Calm Down (feat. Eminem)','Busta Rhymes'],		
    655:['Just What I Am','Kid Cudi, King Chip'],		
    656:['Litty (feat. Tory Lanez)','Meek Mill, Sound M.O.B., Tory Lanez'],		
    657:['Aloha','Charlie Heat, Denzel Curry'],		
    658:['Gimme Some More','Busta Rhymes'],		
    659:['Lord Pretty Flacko Jodye 2 (LPFJ2)','A$AP Rocky'],		
    660:['6 Foot 7 Foot','Lil Wayne, Cory Gunz'],		
    661:['Soldier','Eminem'],		
    662:['Unnatural Born Killer','Yelawolf'],		
    663:['Front & Center','Joey Bada$$'],		
    664:['I Can Tell','Travis Scott'],		
    665:['SPEEDBOAT','Denzel Curry'],		
    666:['RIP Roach','XXXTENTACION, Ski Mask The Slump God'],		
    667:['Hail Mary','2Pac'],		
    668:['NBAYOUNGBOAT','Lil Yachty, YoungBoy Never Broke Again'],		
    669:['BIRDZ FEAT. RICK ROSS','Denzel Curry, Rick Ross'],		
    670:['Tiimmy Turner','Desiigner'],		
    671:['Hit Em Up - Single Version','2Pac, Outlawz'],		
    672:['SUMO | ZUMO','Denzel Curry'],		
    673:['Isis','Joyner Lucas, Logic'],		
    674:['MAD I GOT IT | MAD 1 GOT 1T','Denzel Curry'],		
    675:['Learn How to Watch (feat. Mac Miller & MadeinTYO)','Carnage, Mac Miller, MadeinTYO'],		
    676:['PERCS | PERCZ','Denzel Curry'],		
    677:['And You','Token, IDK, Bas'],		
    678:['Amen','Rich Brian'],		
    679:['Deliver','Lupe Fiasco'],		
    680:['Without Me','Eminem'],		
    681:['Rabbit Run - From 8 Mile Soundtrack','Eminem'],		
    682:['Off Deez (with J. Cole)','JID, J. Cole'],		
    683:['Babushka Boi','A$AP Rocky'],		
    684:['Long Live A$AP','A$AP Rocky'],		
    685:['RAF (feat. A$AP Rocky, Playboi Carti, Quavo, Lil Uzi Vert & Frank Ocean)','A$AP Mob, A$AP Rocky, Playboi Carti, Quavo, Lil Uzi Vert, Frank Ocean'],		
    686:['Lord Knows (feat. Tory Lanez)','Meek Mill, Tory Lanez'],		
    687:['Neon Guts (feat. Pharrell Williams)','Lil Uzi Vert, Pharrell Williams'],		
    688:['Both','Headie One'],		
    689:['151 Rum','JID'],		
    690:['Numb Numb Juice','ScHoolboy Q'],		
    691:['From The D To The A (feat. Lil Yachty)','Tee Grizzley, Lil Yachty'],		
    692:['Left Hand (feat. Joey Bada$$, Flatbush Zombies, The Underachievers, Kirk Knight, Nyck Caution, CJ Fly)','Beast Coast, Joey Bada$$, Flatbush Zombies, The Underachievers, Kirk Knight, Nyck Caution, CJ Fly'],		
    693:['Shoota (feat. Lil Uzi Vert)','Playboi Carti, Lil Uzi Vert'],		
    694:['Faces','Blake'],		
    695:['Fire','KIDS SEE GHOSTS'],		
    696:['SWITCH IT UP | ZWITCH 1T UP','Denzel Curry'],		
    697:['Goldie','A$AP Rocky'],		
    698:['RICKY','Denzel Curry'],		
    699:['123','Smokepurpp, Murda Beatz'],		
    700:['Chef Dreds','Griselda'],		
    701:['ZUU','Denzel Curry'],		
    702:['ULT','Denzel Curry'],		
    703:['Waves','Kanye West'],		
    704:['4th Dimension','KIDS SEE GHOSTS, Louis Prima'],		
    705:['Feel The Love','KIDS SEE GHOSTS, Pusha T'],		
    706:['Black Balloons Reprise','Flying Lotus, Denzel Curry'],		
    707:['Crime Pays','Freddie Gibbs, Madlib'],		
    708:['GANG GANG','JACKBOYS, Sheck Wes'],		
    709:['R.I.P.','Playboi Carti'],		
    710:['November Rain - 2022 Version','Guns N Roses'],		
    711:['Gimme Shelter','The Rolling Stones'],		
    712:['Back In Black','AC/DC'],		
    713:['Creep','Radiohead'],		
    714:['Whole Lotta Love - 1990 Remaster','Led Zeppelin'],		
    715:['Livin On A Prayer','Bon Jovi'],		
    716:['La Grange - 2005 Remaster','ZZ Top'],		
    717:['Hotel California - 2013 Remaster','Eagles'],		
    718:['Hot for Teacher - 2015 Remaster','Van Halen'],		
    719:['All Along the Watchtower','Jimi Hendrix'],		
    720:['Detroit Rock City','KISS'],		
    721:['Wish You Were Here','Pink Floyd'],		
    722:['Master of Puppets (Remastered)','Metallica'],		
    723:['Highway to Hell','AC/DC'],		
    724:['Dont Cry (Original)','Guns N Roses'],		
    725:['Smells Like Teen Spirit','Nirvana'],		
    726:['I Love Rock N Roll','Joan Jett & the Blackhearts'],		
    727:['Dream On','Aerosmith'],		
    728:['The Boys Are Back In Town','Thin Lizzy'],		
    729:['Dont Stop Believin','Journey'],		
    730:['Seven Nation Army','The White Stripes'],		
    731:['Heroes - 2017 Remaster','David Bowie'],		
    732:['Tom Sawyer','Rush'],		
    733:['Are You Gonna Go My Way','Lenny Kravitz'],		
    734:['Killing In The Name','Rage Against The Machine'],		
    735:['Baba ORiley','The Who'],		
    736:['Hungry Heart','Bruce Springsteen'],		
    737:['Hold the Line','TOTO'],		
    738:['Welcome To The Jungle','Guns N Roses'],		
    739:['For What Its Worth','Buffalo Springfield'],		
    740:['Paranoid - 2012 - Remaster','Black Sabbath'],		
    741:['Another One Bites The Dust - Remastered 2011','Queen'],		
    742:['Funk #49','James Gang'],		
    743:['Under the Bridge','Red Hot Chili Peppers'],		
    744:['Everlong','Foo Fighters'],		
    745:['Something In The Way','Nirvana'],		
    746:['Slow Ride','Foghat'],		
    747:['(I Cant Get No) Satisfaction - Mono Version','The Rolling Stones'],		
    748:['Dreams - 2004 Remaster','Fleetwood Mac'],		
    749:['Enter Sandman (Remastered)','Metallica'],		
    750:['Sweet Home Alabama','Lynyrd Skynyrd'],		
    751:['Have You Ever Seen The Rain','Creedence Clearwater Revival'],		
    752:['Every Breath You Take','The Police'],		
    753:['I Wanna Rock','Twisted Sister'],		
    754:['You Really Got Me','The Kinks'],		
    755:['Limelight','Rush'],		
    756:['Black Dog - Remaster','Led Zeppelin'],		
    757:['London Calling - Remastered','The Clash'],		
    758:['Paradise City','Guns N Roses'],		
    759:['Come Together - Remastered 2009','The Beatles'],		
    760:['House Of The Rising Sun','The Animals'],		
    761:['Purple Haze','Jimi Hendrix'],		
    762:['Sultans of Swing','Dire Straits'],		
    763:['Wonderwall - Remastered','Oasis'],		
    764:['One Way Or Another - Remastered/2001','Blondie'],		
    765:['Song 2 - 2012 Remaster','Blur'],		
    766:['Heart-Shaped Box','Nirvana'],		
    767:['Mr. Blue Sky','Electric Light Orchestra'],		
    768:['Free Fallin','Tom Petty'],		
    769:['Edge of Seventeen - 2016 Remaster','Stevie Nicks'],		
    770:['Jailbreak','Thin Lizzy'],		
    771:['Blitzkrieg Bop - 2016 Remaster','Ramones'],		
    772:['Basket Case','Green Day'],		
    773:['Jump - 2015 Remaster','Van Halen'],		
    774:['Stairway to Heaven - Remaster','Led Zeppelin'],		
    775:['Starman - 2012 Remaster','David Bowie'],		
    776:['Godzilla','Blue Öyster Cult'],		
    777:['Purple Rain','Prince'],		
    778:['Bohemian Rhapsody - Remastered 2011','Queen'],		
    779:['We Got The Beat - 2011 Remaster','The Go-Gos'],		
    780:['With Or Without You - Remastered','U2'],		
    781:['Everywhere - 2017 Remaster','Fleetwood Mac'],		
    782:['Crazy On You','Heart'],		
    783:['Kickstart My Heart','Mötley Crüe'],		
    784:['Zombie','The Cranberries'],		
    785:['More Than a Feeling','Boston'],		
    786:['Saturday Night’s Alright (For Fighting) - Remastered 2014','Elton John'],		
    787:['In The Air Tonight - 2015 Remastered','Phil Collins'],		
    788:['Thunderstruck','AC/DC'],		
    789:['Back on the Chain Gang - 2007 Remaster','Pretenders'],		
    790:['Talk','Retronaut, Salvatore Ganacci'],		
    791:['Beggin','Måneskin'],		
    792:['Friends','Chase Atlantic'],		
    793:['Nowhere To Run','Stegosaurus Rex'],		
    794:['Day n Nite','Kid Cudi'],		
    795:['River','Bishop Briggs'],		
    796:['Always Forever','Cults'],		
    797:['What A Shame','Leyla Blue'],		
    798:['Dick (feat. Doja Cat)','StarBoi3, Doja Cat'],		
    799:['All Eyes On Me (Song Only)','Bo Burnham'],		
    800:['Verbatim','Mother Mother'],		
    801:['Break It Off','PinkPantheress'],		
    802:['Thot Shit','Megan Thee Stallion'],		
    803:['Smack a Bitch','Rico Nasty'],		
    804:['Venom - Music From The Motion Picture','Eminem'],		
    805:['I WANNA SEE SOME ASS (feat. jetsonmade)','Jack Harlow, jetsonmade'],		
    806:['I Miss The Rage - Majetso Remix','Majesto Mixer, Mario Judah'],		
    807:['Need to Know','Doja Cat'],		
    808:['Hello Baby feat. Fivio Foreign','Young M.A, Fivio Foreign'],		
    809:['Cigarette Duet','Princess Chelsea'],		
    810:['Knock Knock','SoFaygo'],		
    811:['Bad Girls','M.I.A.'],		
    812:['Can We Kiss Forever?','Kina, Adriana Proenza'],		
    813:['Slow Down','Chase Atlantic'],		
    814:['MONTERO (Call Me By Your Name)','Lil Nas X'],		
    815:['Dark Red','Steve Lacy'],		
    816:['Heat Waves','Glass Animals'],		
    817:['Believe Me','Navos'],		
    818:['Meet Me At Our Spot','THE ANXIETY, WILLOW, Tyler Cole'],		
    819:['My Shit','A Boogie Wit da Hoodie'],		
    820:['Love & War','Yellow Claw, Yade Lauren'],		
    821:['Like I Can','Sam Smith'],		
    822:['She Knows (feat. Amber Coffman & Cults)','J. Cole, Cults, Amber Coffman'],		
    823:['Loverboy','A-Wall'],		
    824:['Love & War - Yellow Claw G-Funk Remix','Yellow Claw, Yade Lauren'],		
    825:['Creatures Lie Here','M.I.K.3, Nicholas Light, Efed'],		
    826:['Cradles','Sub Urban'],		
    827:['Tokyo Drift (Fast & Furious) - From The Fast And The Furious: Tokyo Drift Soundtrack','Teriyaki Boyz'],		
    828:['Drunk And Nasty (feat. Sharc)','Pi’erre Bourne, Sharc'],		
    829:['Work Out','J. Cole'],		
    830:['Supermassive Black Hole','Muse'],		
    831:['From Tha Back','lil.eaarl, Huncho Da Rockstar'],		
    832:['#BrooklynBloodPop!','SyKo'],		
    833:['Miss The Rage (feat. Playboi Carti)','Trippie Redd, Playboi Carti'],		
    834:['MONEY','LISA'],		
    835:['Rhinestone Eyes','Gorillaz'],		
    836:['INFERNO','Sub Urban, Bella Poarch'],		
    837:['love nwantiti (ah ah ah)','CKay'],		
    838:['Sweater Weather','The Neighbourhood'],		
    839:['Frozen - Remix','Edzio'],		
    840:['Oh Klahoma','Jack Stauber'],		
    841:['Spinback','Comethazine'],		
    842:['Everywhereigo','Babyxsosa'],		
    843:['This Could Be Us','Rae Sremmurd'],		
    844:['Go Fuck Yourself','Two Feet'],		
    845:['hot girl bummer','blackbear'],		
    846:['Whyd You Only Call Me When Youre High?','Arctic Monkeys'],		
    847:['Lost in the Fire (feat. The Weeknd)','Gesaffelstein, The Weeknd'],		
    848:['Happier Than Ever','Billie Eilish'],		
    849:['DDLG','ppcocaine'],		
    850:['Honey, Im Good.','Andy Grammer'],		
    851:['Black Out Days - Future Islands Remix','Phantogram, Future Islands'],		
    852:['F33L L1k3 G0D Freestyle','NIECHH'],		
    853:['Big And Chunky','will.i.am'],		
    854:['masquerade','siouxxie sixxsta'],		
    855:['Get Into It (Yuh)','Doja Cat'],		
    856:['Own Brand Freestyle','FelixThe1st, Dréya Mac, Finch Fetti'],		
    857:['abcdefu','GAYLE'],		
    858:['Chin up high','Ame Bibabi'],		
    859:['Enchanted','Taylor Swift'],		
    860:['Infinity','Jaymes Young'],		
    861:['Talk','Retronaut, Salvatore Ganacci'],		
    862:['Beggin','Måneskin'],		
    863:['Friends','Chase Atlantic'],		
    864:['Nowhere To Run','Stegosaurus Rex'],		
    865:['Day n Nite','Kid Cudi'],		
    866:['River','Bishop Briggs'],		
    867:['Always Forever','Cults'],		
    868:['What A Shame','Leyla Blue'],		
    869:['Dick (feat. Doja Cat)','StarBoi3, Doja Cat']		
}

function randomSongList(min,max){
    const songs = [];
    for (let i=0; i<16; i++){
        var n = Math.floor(Math.random() * (max - min + 1)) + min;
        songs.push(allSongs[n]);
    }
    return songs;
}



function changeSong(min, max){
    if (min==1){
        document.body.style.backgroundImage = "url('https://wallpaperaccess.com/full/1584921.jpg')";
    }
    if (min==71){
        document.body.style.backgroundImage = "url('https://i0.wp.com/kjhk.org/web/wp-content/uploads/2020/02/top-50-aotd.png?resize=914%2C458&ssl=1')";
    }
    if (min==147){
        document.body.style.backgroundImage = "url('https://sloclassical.org/wp-content/uploads/2016/02/composerscollage.jpeg')";
    }
    if (min==218){
        document.body.style.backgroundImage = "url('https://i.pinimg.com/736x/09/d5/a7/09d5a7c8ff866185ed23ca7fb9dba7cd.jpg')";
    }
    if (min==283){
        document.body.style.backgroundImage = "url('https://images.unsplash.com/photo-1525361970864-7d5a27a0540f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTd8fGVsZWN0cm9uaWMlMjBtdXNpY3xlbnwwfHwwfHw%3D&w=1000&q=80')";
    }
    if (min==353){
        document.body.style.backgroundImage = "url('https://i.pinimg.com/736x/25/29/32/2529326e24262d9a75db5e2aaeb68b12.jpg')";
    }
    if (min==424){
        document.body.style.backgroundImage = "url('https://wallpaperaccess.com/full/2252971.jpg')";
    }
    if (min==490){
        document.body.style.backgroundImage = "url('https://i.pinimg.com/736x/56/69/24/566924404c512609a40f427ca787e72f.jpg')";
    }
    if (min==565){
        document.body.style.backgroundImage = "url('https://i.pinimg.com/736x/6a/5f/59/6a5f598ca641fabf302f85c5239b6c66.jpg')";
    }
    if (min==630){
        document.body.style.backgroundImage = "url('https://i.etsystatic.com/36820080/r/il/5913e6/4052286312/il_fullxfull.4052286312_cqyo.jpg')";
    }
    if (min==710){
        document.body.style.backgroundImage = "url('https://wallpapercave.com/wp/wp8802916.png')";
    }
    if (min==790){
        document.body.style.backgroundImage = "url('http://cdn.shopify.com/s/files/1/0276/1297/1043/products/tiktokneonsign_1200x1200.png?v=1645150870')";
    }

    songs = randomSongList(min,max);

    var s1 = document.getElementById("s1");
    s1.innerHTML = songs[1][0];
    
    var s2 = document.getElementById("s2");
    s2.innerHTML = songs[2][0];
    
    var s3 = document.getElementById("s3");
    s3.innerHTML = songs[3][0];
    
    var s4 = document.getElementById("s4");
    s4.innerHTML = songs[4][0];
    
    var s5 = document.getElementById("s5");
    s5.innerHTML = songs[5][0];

    var s6 = document.getElementById("s6");
    s6.innerHTML = songs[6][0];
    
    var s7 = document.getElementById("s7");
    s7.innerHTML = songs[7][0];
    
    var s8 = document.getElementById("s8");
    s8.innerHTML = songs[8][0];
    
    var s9 = document.getElementById("s9");
    s9.innerHTML = songs[9][0];
    
    var s10 = document.getElementById("s10");
    s10.innerHTML = songs[10][0];

    var s11 = document.getElementById("s11");
    s11.innerHTML = songs[11][0];
    
    var s12 = document.getElementById("s12");
    s12.innerHTML = songs[12][0];
    
    var s13 = document.getElementById("s13");
    s13.innerHTML = songs[13][0];
    
    var s14 = document.getElementById("s14");
    s14.innerHTML = songs[14][0];
    
    var s15 = document.getElementById("s15");
    s15.innerHTML = songs[15][0];

    var a1 = document.getElementById("a1");
    a1.innerHTML = songs[1][1];
    
    var a2 = document.getElementById("a2");
    a2.innerHTML = songs[2][1];
    
    var a3 = document.getElementById("a3");
    a3.innerHTML = songs[3][1];
    
    var a4 = document.getElementById("a4");
    a4.innerHTML = songs[4][1];
    
    var a5 = document.getElementById("a5");
    a5.innerHTML = songs[5][1];

    var a6 = document.getElementById("a6");
    a6.innerHTML = songs[6][1];
    
    var a7 = document.getElementById("a7");
    a7.innerHTML = songs[7][1];
    
    var a8 = document.getElementById("a8");
    a8.innerHTML = songs[8][1];
    
    var a9 = document.getElementById("a9");
    a9.innerHTML = songs[9][1];
    
    var a10 = document.getElementById("a10");
    a10.innerHTML = songs[10][1];

    var a11 = document.getElementById("a11");
    a11.innerHTML = songs[11][1];
    
    var a12 = document.getElementById("a12");
    a12.innerHTML = songs[12][1];
    
    var a13 = document.getElementById("a13");
    a13.innerHTML = songs[13][1];
    
    var a14 = document.getElementById("a14");
    a14.innerHTML = songs[14][1];
    
    var a15 = document.getElementById("a15");
    a15.innerHTML = songs[15][1];
}